# Generated by Django 3.1 on 2020-08-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='item_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
