# Generated by Django 3.1 on 2020-08-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_winner_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
