# Generated by Django 3.1 on 2020-08-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionitem_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='category',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='price',
        ),
        migrations.AddField(
            model_name='winner',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionitem'),
            preserve_default=False,
        ),
    ]
